name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-with-cmake:
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: cmake
      run: cmake -B build
    - name: make
      run: cmake --build build
    - name: ctest
      run: ctest
      working-directory: build
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest

  build-with-bazel:
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: bazel build -c opt //main:demo
    - name: test
      run: bazel test -c opt //lib:demo-lib-test
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
